import xlsx from 'xlsx';
import { initSQLServer, getSQLPool } from '../src/config/sqlserver.js';

console.log('🚀 Starting MINIMAL Excel contact import...');

try {
  // 1. Read Excel file
  console.log('📁 Reading Excel file...');
  const workbook = xlsx.readFile('../Phone Contacts Business.xlsx');
  console.log('📋 Available sheets:', workbook.SheetNames.join(', '));
  
  // 2. Get Sheet2 specifically
  const sheetName = 'Sheet2';
  const worksheet = workbook.Sheets[sheetName];
  const data = xlsx.utils.sheet_to_json(worksheet);
  
  console.log(`📊 Found ${data.length} contacts in Sheet2`);
  console.log('🔍 Sample Excel columns:', Object.keys(data[0]));
  console.log('📄 First row data:', data[0]);

  // 3. Initialize database
  console.log('🔌 Initializing database...');
  await initSQLServer();
  console.log('✅ Database initialized successfully');
  
  const pool = await getSQLPool();
  console.log('✅ Database connected successfully');
  
  // 4. Get existing contacts
  console.log('📇 Loading existing contacts...');
  const existingContacts = await pool.request()
    .query(`SELECT id, phone_number, display_name FROM contacts`);
  
  console.log(`📇 Found ${existingContacts.recordset.length} existing contacts`);
  
  // 5. Process just first 5 contacts
  console.log('🔄 Processing first 5 contacts...');
  
  for (let i = 0; i < Math.min(5, data.length); i++) {
    const row = data[i];
    
    const phone = String(row['Mobile Number'] || '').replace(/[^\d]/g, '');
    const name = row.Name || '';
    
    console.log(`📝 Contact ${i+1}: Phone=${phone}, Name=${name}`);
    
    if (!phone || !name) {
      console.log(`⚠️ Skipping - missing data`);
      continue;
    }
    
    // Check if exists
    const existing = existingContacts.recordset.find(c => 
      String(c.phone_number).replace(/[^\d]/g, '') === phone
    );
    
    if (existing) {
      console.log(`✏️ Updating: ${existing.display_name} → ${name}`);
      await pool.request()
        .input('id', existing.id)
        .input('name', name)
        .input('isAutoGenerated', 1)
        .query(`
          UPDATE contacts
          SET display_name = @name, is_auto_generated = @isAutoGenerated
          WHERE id = @id
        `);
    } else {
      console.log(`➕ Creating new: ${phone} - ${name}`);
      await pool.request()
        .input('phone', phone)
        .input('name', name)
        .input('isAutoGenerated', 1)
        .query(`
          INSERT INTO contacts (display_name, phone_number, is_auto_generated)
          VALUES (@name, @phone, @isAutoGenerated)
        `);
    }
  }
  
  console.log('🎉 MINIMAL import completed!');
  
} catch (error) {
  console.error('❌ Error:', error.message);
  console.error('🔍 Full error:', error);
  process.exit(1);
}
