import xlsx from 'xlsx';
import { initSQLServer, getSQLPool } from '../src/config/sqlserver.js';

console.log('🚀 Starting BATCH Excel contact import...');

try {
  // 1. Read Excel file
  console.log('📁 Reading Excel file...');
  const workbook = xlsx.readFile('../Phone Contacts Business.xlsx');
  console.log('📋 Available sheets:', workbook.SheetNames.join(', '));
  
  // 2. Get Sheet2 specifically
  const sheetName = 'Sheet2';
  const worksheet = workbook.Sheets[sheetName];
  const data = xlsx.utils.sheet_to_json(worksheet);
  
  console.log(`📊 Found ${data.length} contacts in Sheet2`);

  // 3. Initialize database
  console.log('🔌 Initializing database...');
  await initSQLServer();
  console.log('✅ Database initialized successfully');
  
  const pool = await getSQLPool();
  console.log('✅ Database connected successfully');
  
  // 4. Get existing contacts
  console.log('📇 Loading existing contacts...');
  const existingContacts = await pool.request()
    .query(`SELECT id, phone_number, display_name FROM contacts`);
  
  console.log(`📇 Found ${existingContacts.recordset.length} existing contacts`);
  
  // Create phone map for fast lookup
  const existingMap = new Map();
  existingContacts.recordset.forEach(contact => {
    const normalizedPhone = String(contact.phone_number).replace(/[^\d]/g, '');
    if (normalizedPhone) {
      existingMap.set(normalizedPhone, contact);
    }
  });
  
  // 5. Process in batches
  let matched = 0;
  let updated = 0;
  let created = 0;
  let skipped = 0;
  const batchSize = 100;
  
  console.log(`🔄 Processing ${data.length} contacts in batches of ${batchSize}...`);
  
  for (let start = 0; start < data.length; start += batchSize) {
    const end = Math.min(start + batchSize, data.length);
    const batch = data.slice(start, end);
    
    console.log(`📈 Processing batch ${Math.floor(start/batchSize) + 1}/${Math.ceil(data.length/batchSize)} (contacts ${start+1}-${end})`);
    
    for (let i = 0; i < batch.length; i++) {
      const row = batch[i];
      const globalIndex = start + i;
      
      const phone = String(row['Mobile Number'] || '').replace(/[^\d]/g, '');
      const name = (row.Name || '').trim();
      
      if (!phone || !name) {
        skipped++;
        continue;
      }
      
      const existing = existingMap.get(phone);
      
      if (existing) {
        // Update if different
        if (existing.display_name !== name) {
          await pool.request()
            .input('id', existing.id)
            .input('name', name)
            .input('isAutoGenerated', 1)
            .query(`
              UPDATE contacts
              SET display_name = @name, is_auto_generated = @isAutoGenerated
              WHERE id = @id
            `);
          updated++;
        }
        matched++;
      } else {
        // Create new
        await pool.request()
          .input('phone', phone)
          .input('name', name)
          .input('isAutoGenerated', 1)
          .query(`
            INSERT INTO contacts (display_name, phone_number, is_auto_generated)
            VALUES (@name, @phone, @isAutoGenerated)
          `);
        created++;
      }
    }
    
    // Show progress after each batch
    console.log(`✅ Batch completed. Total so far: ${matched} matched, ${updated} updated, ${created} created, ${skipped} skipped`);
  }
  
  console.log('\n🎉 === FINAL IMPORT SUMMARY ===');
  console.log(`📊 Total Excel contacts: ${data.length}`);
  console.log(`🎯 Matched with existing: ${matched}`);
  console.log(`✏️ Updated: ${updated}`);
  console.log(`➕ Created new: ${created}`);
  console.log(`⚠️ Skipped (invalid): ${skipped}`);
  console.log(`📇 Existing in DB: ${existingContacts.recordset.length}`);
  console.log('============================\n');
  
} catch (error) {
  console.error('❌ Error:', error.message);
  console.error('🔍 Full error:', error);
  process.exit(1);
}
